### ISSUE TITLE
duplicatequestion - qbank plugin build

### ISSUE THREAD

**Issue by safatshahin** [catalyst/moodle-MDL-70329#81] opened 2021-05-12 09:20 UTC

**Comment by safatshahin** [comment] 2021-05-13 06:31
PR #83

**Comment by mattporritt** [comment] 2021-05-16 06:22
@safatshahin and @guillogo I've removed the individual tracker for this. This PR will need to be merged into the MDL-71574 branch along with issue #54 and issue #50

**Comment by guillogo** [comment] 2021-05-24 05:12
Hi @safatshahin 

Tested and approved issues:

- https://github.com/catalyst/moodle-MDL-70329/issues/54
- https://github.com/catalyst/moodle-MDL-70329/issues/50
- https://github.com/catalyst/moodle-MDL-70329/issues/81

TODO:

1. Merge.
2. Add the ready for tracker check list.

Thank you.

**Comment by safatshahin** [comment] 2021-05-24 05:20
Checklist added in #54

**Comment by safatshahin** [comment] 2021-05-27 04:41
implemented in the editquestion plugin as a part of #54 
issue can be closed.

**Comment by abonaccorso** [comment] 2021-07-30 10:22
Hi @safatshahin there seems to be an issue with duplicating questions in a question bank activity. It seems that I does not always display more than one tag in the questions overview in the question bank (I tested with essay, shortanswer and truefalse. Sometimes it works fine, sometimes the below bug appears. I did not succeed in understanding, when it works and when not)

**How to reproduce**
1. Create a question bank activity.
2. Click on the activity
3. Add an essay question with two tags, save.
4. Duplicate the question (don't change anything while duplicating)
4. Have a look at the duplicated question in the questions overview of the question bank (visible once you saved the duplicated question)
5. instead of the second tag, you can only see "..." for the duplicated question

![grafik](https://user-images.githubusercontent.com/13217187/127639511-117daa52-c957-4132-8a69-19b61f4d47b5.png)

the course where I tested is: https://quiz4.catalyst-au.net/mod/qbank/view.php?id=601

**Comment by abonaccorso** [comment] 2021-07-30 13:52
Additional information: The same thing happened to me, when I
1. created a quiz
2. added a question with 3 tags (via add a question, thus stored in the quiz level question bank)
3. deleted the quiz
4. looked at the question that was in the quiz but now was moved to another category in the (old) course level question bank

**Comment by abonaccorso** [comment] 2021-07-30 14:04
I realized that this is not a bug, but due to the fact, that there is not enough space to display the second (third, and so on) tag. So it is not a bug --> Closing

**Comment by mattporritt** [comment] 2021-08-31 04:35
integrated

**Closed by mattporritt** 2021-08-31 04:35 UTC
Labels: Development, qbank_*, MDL-71574
